[package]
name = "bevy_ahoy"
authors = ["Jan Hohenheim <jan@hohenheim.ch>"]
version = "0.0.2"
edition = "2024"
license = "MIT OR Apache-2.0 "
description = "A fun 3D Kinematic Character Controller for Bevy + Avian + BEI."
readme = "readme.md"
repository = "https://github.com/janhohenheim/bevy_ahoy"
keywords = ["kcc", "character", "controller", "source", "quake"]
categories = ["game-development"]
include = ["/src", "/license*", "/examples"]

[dependencies]
avian3d = { git = "https://github.com/slyedoc/avian", branch = "solari-multi", default-features = false, features = ["parry-f32", "3d"] }
bevy_ecs = { git = "https://github.com/bevyengine/bevy", branch = "main", default-features = false, features = ["bevy_reflect"] }
bevy_app = { git = "https://github.com/bevyengine/bevy", branch = "main", default-features = false }
bevy_derive = { git = "https://github.com/bevyengine/bevy", branch = "main", default-features = false }
bevy_utils = { git = "https://github.com/bevyengine/bevy", branch = "main", default-features = false }
bevy_math = { git = "https://github.com/bevyengine/bevy", branch = "main", default-features = false, features = ["std"] }
bevy_reflect = { git = "https://github.com/bevyengine/bevy", branch = "main", default-features = false }
bevy_transform = { git = "https://github.com/bevyengine/bevy", branch = "main", default-features = false }
bevy_time = { git = "https://github.com/bevyengine/bevy", branch = "main", default-features = false }
bevy_enhanced_input = { git = "https://github.com/slyedoc/bevy_enhanced_input", branch = "bevy-main", default-features = false }
tracing = { version = "0.1", default-features = false }
avian_pickup = { git = "https://github.com/slyedoc/avian_pickup", branch = "solari-multi" }


[dev-dependencies]
bevy = { git = "https://github.com/bevyengine/bevy", branch = "main", features = ["track_location", "dynamic_linking", "file_watcher"] }
bevy_trenchbroom = "0.11.0"
bevy_trenchbroom_avian = "0.11.0"
bevy_mod_mipmap_generator = { git = "https://github.com/slyedoc/bevy_mod_mipmap_generator", branch = "bevy-main" }
avian3d = { git = "https://github.com/slyedoc/avian", branch = "solari-multi" }
bevy_framepace = "0.20.0"
bevy_fix_cursor_unlock_web = "0.2.0"
wasm-bindgen = "=0.2.108"

[package.metadata.bevy_cli.unstable]
#web-multi-threading = true

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[lints.rust]
# missing_docs = "warn"
unused_qualifications = "warn"

[lints.clippy]
too_many_arguments = "allow"
type_complexity = "allow"
needless_lifetimes = "allow"
doc_markdown = "warn"
manual_let_else = "warn"
match_same_arms = "warn"
redundant_closure_for_method_calls = "warn"
redundant_else = "warn"
semicolon_if_nothing_returned = "warn"
undocumented_unsafe_blocks = "warn"
unwrap_or_default = "warn"
nonstandard_macro_braces = "warn"
ptr_as_ptr = "warn"
ptr_cast_constness = "warn"
ref_as_ptr = "warn"
too_long_first_doc_paragraph = "allow"
allow_attributes = "warn"
allow_attributes_without_reason = "warn"

[package.metadata.docs.rs]
rustdoc-args = ["-Zunstable-options", "--generate-link-to-definition"]
all-features = true

[patch.crates-io]
avian3d = { git = "https://github.com/slyedoc/avian", branch = "solari-multi" }
parry3d = { git = "https://github.com/slyedoc/parry", branch = "bevy-main" }
parry3d-f64 = { git = "https://github.com/slyedoc/parry", branch = "bevy-main" }
glamx = { git = "https://github.com/slyedoc/glamx", branch = "bevy-main" }
